#!/bin/bash


_LEGEND_zip () {
    if [[ $GIT_REPO ]]
    then
        echo "https://github.com/${GIT_REPO}/archive/master.zip"
    else
        echo "https://github.com/badmunda011/LEGEND-BOT/archive/master.zip" 
    fi
}

_library () {
    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then 
        python3 -m PyrogramLEGEND
    else
        python3 -m TelethonLEGEND
    fi
}

_starter () {
    local LEGENDPATH
    LEGENDPATH="Plugins.zip"
    echo "••• DOWNLOADING PBXBOT •••"
    wget -q $(_Pbx_zip) -O "$LEGENDPATH"
    LEGENDPATH=$(zipinfo -1 "$LEGENDPATH" | grep -v "/.");
    unzip -qq "$LEGENDPATH"
    rm -rf "$LEGENDPATH"
    cd $LEGENDPATH
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING PBXBOT •••"
    _library
}

_starter
